<?php
/**
 * Created by Oleg Dudkin.
 * Project: CMS "DON e-Commerce"
 * File name: views.php
 * Date: 8/3/2017
 * Time: 1:56 PM
 */

class Views extends \don\core\BaseView
{
    function render($view, $args=array())
    {
        parent::render($view, $args); // TODO: Change the autogenerated stub
    }
}